# Generated by Django 5.1.5 on 2025-02-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='slug',
            field=models.SlugField(blank=True, max_length=35, null=True),
        ),
    ]
