# Generated by Django 5.1.5 on 2025-02-27 04:55

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ', unique=True),
        ),
    ]
