# Generated by Django 5.1.5 on 2025-02-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_comment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
